{{- if .Values.distributed.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "octantis.fullname" . }}-worker
  labels:
    {{- include "octantis.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.distributed.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "octantis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "octantis.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.octantis.metrics.port | quote }}
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ include "octantis.serviceAccountName" . }}
      containers:
        - name: worker
          image: "{{ .Values.octantis.image.repository }}:{{ include "octantis.imageTag" . }}"
          imagePullPolicy: {{ .Values.octantis.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.octantis.metrics.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "octantis.fullname" . }}
            - configMapRef:
                name: {{ include "octantis.fullname" . }}-distributed
          env:
            - name: OCTANTIS_MODE
              value: worker
            {{- range $key, $secret := .Values.secrets }}
            {{- if $secret.existingSecret }}
            - name: {{ $secret.key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret.existingSecret }}
                  key: {{ $secret.key }}
            {{- else if $secret.externalsecret.create }}
            - name: {{ $secret.key }}
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" (include "octantis.fullname" $) $key }}
                  key: {{ $secret.key }}
            {{- else if $secret.create }}
            - name: {{ $secret.key }}
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" (include "octantis.fullname" $) $key }}
                  key: {{ $secret.key }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.distributed.worker.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 10
{{- end }}
