{{- range $key, $secret := .Values.secrets }}
{{- if and $secret.create (not $secret.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "octantis.fullname" $) $key }}
  labels:
    {{- include "octantis.labels" $ | nindent 4 }}
    app.kubernetes.io/component: octantis
type: Opaque
stringData:
  {{ $secret.key }}: {{ $secret.value | quote }}
{{- end }}
{{- end }}
