{{- if and .Values.otelOperator.enabled .Values.otelCollector.enabled }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "octantis.fullname" . }}-collector
  labels:
    {{- include "octantis.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  mode: {{ .Values.otelCollectorCR.mode }}
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      {{- if and .Values.kubePrometheusStack.enabled .Values.kubePrometheusStack.prometheus.enabled }}
      prometheus:
        config:
          scrape_configs:
            - job_name: "kube-prometheus-stack"
              scrape_interval: 30s
              static_configs:
                - targets:
                    - {{ printf "%s-prometheus:9090" (include "octantis.fullname" .) }}
      {{- end }}
    exporters:
      otlp:
        endpoint: {{ printf "http://%s:%d" (include "octantis.fullname" .) (int .Values.octantis.otlp.grpc.port) }}
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers:
            - otlp
            {{- if and .Values.kubePrometheusStack.enabled .Values.kubePrometheusStack.prometheus.enabled }}
            - prometheus
            {{- end }}
          exporters:
            - otlp
        logs:
          receivers:
            - otlp
          exporters:
            - otlp
{{- end }}
