{{- range $key, $secret := .Values.secrets }}
{{- if and $secret.externalsecret.create (not $secret.existingSecret) }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s" (include "octantis.fullname" $) $key }}
  labels:
    {{- include "octantis.labels" $ | nindent 4 }}
    app.kubernetes.io/component: octantis
spec:
  refreshInterval: {{ $secret.externalsecret.spec.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $secret.externalsecret.spec.secretStoreRef.name }}
    kind: {{ $secret.externalsecret.spec.secretStoreRef.kind | default "SecretStore" }}
  target:
    name: {{ printf "%s-%s" (include "octantis.fullname" $) $key }}
    creationPolicy: Owner
  data:
    - secretKey: {{ $secret.key }}
      remoteRef:
        key: {{ $secret.externalsecret.spec.remoteRef.key }}
        {{- if $secret.externalsecret.spec.remoteRef.property }}
        property: {{ $secret.externalsecret.spec.remoteRef.property }}
        {{- end }}
{{- end }}
{{- end }}
